Chore add cli ascii art
bonfhir/bonfhir pull request #74
Opened 2023-09-12 21:24 UTC by BlueMona

This PR adds some simple ascii art of the bonFHIR logo to liven up the display text in the command-line interface. Figlet was used as a tool to generate the initial text, which was modified with the addition of some original "fire" text.

2023-09-13 11:50 UTC, julienblin requested changes
Thanks a lot!
I added a comment about extracting it in its own file.

Also - the reason the PR is failing is because there is no changeset. I'll walk you through it today.

2023-09-13 11:50 UTC, julienblin commented on packages/cli/src/commands/create.ts
> +    console.log("       \|\\         _                    _____  _   _  ___  ____        \|\\");
I would probably recommend that this is extracted into its own function in a separate file.

2023-09-13 19:49 UTC, julienblin requested changes
Thanks!
So the code is good - thank you for this.

I do have a request though:
 - could you just have 1 commit instead of 3?
 - also - your github email is still mona@capablehealth.com - maybe you could change it before pushing the updated commits?
 
Thank you!

2023-09-14 15:26 UTC, BlueMona commented
> Thanks! So the code is good - thank you for this.
> 
> I do have a request though:
> 
> * could you just have 1 commit instead of 3?
Squash merge should fix this? 
> * also - your github email is still [mona@capablehealth.com](mailto:mona@capablehealth.com) - maybe you could change it before pushing the updated commits?
I thought I changed that but wonder if it was only on a per-repo basis. I'll look into that.

2023-09-14 17:26 UTC, ysael approved these changes

2023-09-14 19:54 UTC, julienblin approved these changes
This is great! Thank you 🥳 !

2023-09-15 14:54 UTC, merged