Add optional buttons to questionnaire
bonfhir/bonfhir pull request #80
Opened 2023-09-19 18:38 UTC by stephanie-saretsky

This PR adds the option to add `save as draft` and `delete` buttons to the questionnaire, with the user able to pass the actions and text down as props in the same pattern as the submit & cancel button s

2023-09-20 13:56 UTC, julienblin requested changes
Hey Stephanie - thanks for your PR!

At this point though, I would rather go with a more generic solution - aligned with what the original issue describes.

I'll be happy to provide some help, but I feel we should allow for the app using the component to _inject_ whatever buttons they want. Otherwise, we will keep adding new use cases every time.
Can you come up with a design that allows this?

2023-09-20 15:43 UTC, ysael approved these changes
lgtm

2023-09-25 13:14 UTC, julienblin requested changes
Thank you!
This is better, but I still think it misses some of the original issue features - namely the ability to completely customize the actions strip - not just add buttons.

Also - I believe we should pass the `form` instance to that customization to allow consuming code to interact with the form instance (invalidate, get values, etc.)

2023-09-25 15:04 UTC, stephanie-saretsky commented
Alright! I will update the issue as I understood it was to just add buttons, I will make it more clear

2023-10-13 12:05 UTC, julienblin commented
@stephanie-saretsky - I realize I did not answer the question you asked.
The override should override all the buttons, including the two that are provided by default.

2023-11-21 19:47 UTC, stephanie-saretsky commented
Closing due to my lack of time to tackle this issue over this time period, will open a new one when time allows

2023-11-21 19:47 UTC, closed without merging